### ISSUE TITLE
it looks like openweathermap changed to the OneCall 3.0 API

### ISSUE THREAD

**Issue by revere521** [FlatPepsi17/MMM-WeatherGraph#8]
it looks like openweathermap changed to the OneCall 3.0 API - which is now a "free" subscription that requires payment over a number of calls per day.  the api response for https://api.openweathermap.org/data/3.0/onecall?lat={lat]&lon={lon}&appid={API Key} now returns:

"Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price."

https://api.openweathermap.org/data/2.5/onecall?lat={lat]&lon={lon}&appid={API Key} no longer works at all (401 error)

**Comment by revere521** [comment]
https://openweathermap.org/api/one-call-api  this is the info about onecall 2.5 being replaced with 3.0

**Comment by zuch95701** [comment]
I just went into the MMM-WeatherGraph module and the Json for it, all i had to do was update the API url from "2.5" to "3.0" after signing up on openweathers website, limit your calls to every 5 mins and you wont exceed the 1000 a day free limit. Module seems to be working fine with no errors.

**Comment by revere521** [comment]
i can confirm that works, the file is MMM-WeatherGrapg.js in the module folder, change the 2.5 in the base URL to 3.0 and subscribe.  I think the default call time period if 15 minutes, so that's all set.   Thanks!

**Comment by FlatPepsi17** [comment]
fixed in main branch
